### ISSUE TITLE
聊聊renpy的加密

### ISSUE THREAD

**Issue by ksksone** [ZYKsslm/RenPyUtil#1]
聊聊renpy的加密
感觉加密其实没有特别大的用处，或者是不想公开自己的游戏素材？但是对粉丝翻译来说就会麻烦，除非联系原作者；
可能为了防止倒狗？但是倒狗基本都不管售后，加不加密都不影响倒卖。还有就是怕自己的翻译文件被偷

**Comment by ZYKsslm** [comment]
是的，由于renpy和python的开源特性无论怎样都无法保证绝对安全。加密模块初衷在于保护资源文件，增加破解成本，rpyc文件暂时无法使用，而且现在貌似出了一些亟待解决的BUG。

**Comment by ksksone** [comment]
> 是的，由于renpy和python的开源特性无论怎样都无法保证绝对安全。加密模块初衷在于保护资源文件，增加破解成本，rpyc文件暂时无法使用，而且现在貌似出了一些亟待解决的BUG。

期待后续更新
